# Generated by Django 4.2.2 on 2025-09-15 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["country"], "verbose_name": "Пользователь", "verbose_name_plural": "Пользователи"},
        ),
    ]
