# Generated by Django 4.2.2 on 2025-09-15 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={"ordering": ["full_name"], "verbose_name": "Клиент", "verbose_name_plural": "Клиенты"},
        ),
        migrations.AlterModelOptions(
            name="mailing",
            options={"ordering": ["owner"], "verbose_name": "Рассылка", "verbose_name_plural": "Рассылки"},
        ),
        migrations.AlterModelOptions(
            name="mailingattempt",
            options={"ordering": ["attempt_time"], "verbose_name": "Попытка", "verbose_name_plural": "Попытки"},
        ),
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["owner"], "verbose_name": "Сообщение", "verbose_name_plural": "Сообщения"},
        ),
    ]
